name: Update WNBA Data

on:
  workflow_dispatch:
    inputs:
      start_year:
        required: false
        type: string
      end_year:
        required: false
        type: string
      rescrape:
        required: false
        default: true
        type: boolean

jobs:
  update_wnba_data:
    runs-on: ${{ matrix.config.os }}
    name: Update WNBA Data
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      START_YEAR: ${{ inputs.start_year }}
      END_YEAR: ${{ inputs.end_year }}
      RESCRAPE: ${{ inputs.rescrape }}

    steps:
      - name: Check for Inputs
        if: ${{ env.START_YEAR == ''}}
        run: |
          echo START_YEAR=$(date +'%Y') >> $GITHUB_ENV
          echo END_YEAR=$(date +'%Y') >> $GITHUB_ENV
      - name: Print New Env Vars
        run: |
          echo ${{ env.START_YEAR }}
          echo ${{ env.END_YEAR }}
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setting up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Setting up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            sportsdataverse/wehoop
            sportsdataverse/sportsdataverse-data
            ropensci/piggyback

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      # Tells Github to run the file `scraper.py` from your repository
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
      - name: Getting Schedules
        run: |
          python python/scrape_wnba_schedules.py -s ${{ env.START_YEAR }} -e ${{ env.END_YEAR }}
      - name: Getting PBP
        run: |
          python python/scrape_wnba_json.py -s ${{ env.START_YEAR }} -e ${{ env.END_YEAR }} -r ${{ env.RESCRAPE }}
      - name: Compiling PBP data
        env:
          GITHUB_PAT: ${{ secrets.SDV_GH_TOKEN }}
        run: |
          Rscript R/espn_wnba_01_pbp_creation.R -s ${{ env.START_YEAR }} -e ${{ env.END_YEAR }}
      - name: Compiling Team Boxscore data
        env:
          GITHUB_PAT: ${{ secrets.SDV_GH_TOKEN }}
        run: |
          Rscript R/espn_wnba_02_team_box_creation.R -s ${{ env.START_YEAR }} -e ${{ env.END_YEAR }}
      - name: Compiling Player Boxscore data
        env:
          GITHUB_PAT: ${{ secrets.SDV_GH_TOKEN }}
        run: |
          Rscript R/espn_wnba_03_player_box_creation.R -s ${{ env.START_YEAR }} -e ${{ env.END_YEAR }}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add .
          git commit -m "WNBA Data Updated (Start: ${{ env.START_YEAR }} End: ${{ env.END_YEAR }})" || echo "No changes to commit"
          git pull --rebase
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SDV_GH_TOKEN }}
